project:
  type: website
  
execute: 
  freeze: auto

website:
  favicon: logo.png
  twitter-card: true
  site-url: https://example.com
  sidebar: 
    style: "floating"
    search: false
    contents: 
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

