project:
  type: website
  

website:
  repo-url: https://github.com/joshyam-k/personal-website
  sidebar: 
    style: "docked"
    pinned: true
    border: false
    search: false
    contents: 
      - href: index.qmd
        text: "Home"
      - href: resume.qmd
        text: "About"
      - href: blog.qmd
        text: "Blog"
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    fontsize: 1.3em
    mainfont: monospace
    css: styles.css
    toc: true

editor: visual

