project:
  type: website
  
execute: 
  freeze: auto

website:
  sidebar: 
    style: "docked"
    contents: 
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: blog.qmd
        text: "Blog"
format:
  html:
    theme: cosmo
    mainfont: monospace
    css: styles.css
    toc: true

editor: visual

